import { useState, useMemo } from "react";
import reactLogo from "../assets/react.svg";
import viteLogo from "../assets/vite.svg";
// import '../styles/App.css'
import { Button } from "@/components/ui/button";
import LandingPages from "./landingPage/Faq";
import { buttonVariants } from "@/components/ui/button";
import { Link } from "lucide-react";
import Navbar from "@/components/ui/navbar";
import Hero from "@/components/landing-page/hero";
import GetApps from "@/components/landing-page/get-apps";
import { Input } from "@/components/ui/input";
import TableQuiz from "@/components/tables";
import Layout from "@/components/layout/Index";
import { Check, X } from "lucide-react";

import { createColumnHelper } from "@tanstack/react-table";

function App() {
  const [count, setCount] = useState(0);

  const realData = [
    {
      nama: "Camilla Wigfall",
      skor: 7,
      jawaban: [
        false,
        false,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
      ],
    },
    {
      nama: "Corette Hobble",
      skor: 74,
      jawaban: [
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
      ],
    },
    {
      nama: "Antin Yabsley",
      skor: 65,
      jawaban: [
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        true,
        false,
        true,
      ],
    },
    {
      nama: "Corry Pea",
      skor: 63,
      jawaban: [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
      ],
    },
    {
      nama: "Dacy Amber",
      skor: 13,
      jawaban: [
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
      ],
    },
    {
      nama: "Nikki Lampard",
      skor: 31,
      jawaban: [
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
      ],
    },
    {
      nama: "Sherilyn Killock",
      skor: 83,
      jawaban: [
        true,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
      ],
    },
    {
      nama: "Gearalt Coverdale",
      skor: 39,
      jawaban: [
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
      ],
    },
    {
      nama: "Bondy Cammoile",
      skor: 89,
      jawaban: [
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        true,
        false,
        true,
        true,
      ],
    },
    {
      nama: "Sylvia Blasing",
      skor: 57,
      jawaban: [
        false,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    },
    {
      nama: "Eolande Nannizzi",
      skor: 48,
      jawaban: [
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        false,
      ],
    },
    {
      nama: "Joyan Santore",
      skor: 91,
      jawaban: [
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
      ],
    },
    {
      nama: "Elisabet Helwig",
      skor: 64,
      jawaban: [
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
      ],
    },
    {
      nama: "Feodora Guidotti",
      skor: 93,
      jawaban: [
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
      ],
    },
    {
      nama: "Annabela Soltan",
      skor: 65,
      jawaban: [
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
      ],
    },
    {
      nama: "Brewer Searight",
      skor: 57,
      jawaban: [
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
      ],
    },
    {
      nama: "Ad Dudderidge",
      skor: 86,
      jawaban: [
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
      ],
    },
    {
      nama: "Robinett Ivantyev",
      skor: 57,
      jawaban: [
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        true,
      ],
    },
    {
      nama: "Nadya Woolrich",
      skor: 89,
      jawaban: [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
      ],
    },
    {
      nama: "Bond Ennals",
      skor: 95,
      jawaban: [
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        true,
        true,
        false,
        true,
        true,
      ],
    },
    {
      nama: "Bailey Clayton",
      skor: 12,
      jawaban: [
        false,
        false,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
      ],
    },
    {
      nama: "Dody Ewles",
      skor: 40,
      jawaban: [
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
      ],
    },
    {
      nama: "Kennett Le Conte",
      skor: 16,
      jawaban: [
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        true,
        false,
      ],
    },
    {
      nama: "Kendell Vallow",
      skor: 89,
      jawaban: [
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
      ],
    },
    {
      nama: "Adele Holsey",
      skor: 28,
      jawaban: [
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
      ],
    },
    {
      nama: "Yvonne Palay",
      skor: 25,
      jawaban: [
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        true,
        false,
        true,
        true,
      ],
    },
    {
      nama: "Rooney Manifould",
      skor: 78,
      jawaban: [
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
      ],
    },
    {
      nama: "August Calderwood",
      skor: 21,
      jawaban: [
        true,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        false,
        true,
        false,
        true,
        false,
        false,
      ],
    },
    {
      nama: "Elfreda Hanny",
      skor: 75,
      jawaban: [
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
      ],
    },
    {
      nama: "Lotta Rudkin",
      skor: 66,
      jawaban: [
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
      ],
    },
    {
      nama: "Cassaundra Issatt",
      skor: 0,
      jawaban: [
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        false,
      ],
    },
    {
      nama: "Gizela Norquay",
      skor: 6,
      jawaban: [
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
      ],
    },
    {
      nama: "Ellerey Davioud",
      skor: 41,
      jawaban: [
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        true,
        false,
      ],
    },
    {
      nama: "Rafa Peterffy",
      skor: 62,
      jawaban: [
        false,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        true,
        false,
      ],
    },
    {
      nama: "Kaycee Soggee",
      skor: 13,
      jawaban: [
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
      ],
    },
    {
      nama: "Layla Kezourec",
      skor: 74,
      jawaban: [
        true,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
    },
    {
      nama: "Ethelind Trenbey",
      skor: 93,
      jawaban: [
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        true,
      ],
    },
    {
      nama: "Art Ackred",
      skor: 79,
      jawaban: [
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
      ],
    },
    {
      nama: "Filbert Grishmanov",
      skor: 33,
      jawaban: [
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
      ],
    },
    {
      nama: "Leoline Redparth",
      skor: 72,
      jawaban: [
        true,
        false,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
    },
    {
      nama: "Stewart Dyka",
      skor: 31,
      jawaban: [
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
      ],
    },
    {
      nama: "Ray Crosbie",
      skor: 24,
      jawaban: [
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
      ],
    },
    {
      nama: "Merle Yurocjkin",
      skor: 27,
      jawaban: [
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
      ],
    },
    {
      nama: "Elihu Ruvel",
      skor: 37,
      jawaban: [
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
      ],
    },
    {
      nama: "Zonnya Bagger",
      skor: 68,
      jawaban: [
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
      ],
    },
    {
      nama: "Brandi Sandlin",
      skor: 33,
      jawaban: [
        false,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        true,
        true,
        false,
      ],
    },
    {
      nama: "Giles Plaskitt",
      skor: 15,
      jawaban: [
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
      ],
    },
    {
      nama: "Sheila Farris",
      skor: 99,
      jawaban: [
        false,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
      ],
    },
    {
      nama: "Pietra de Clerq",
      skor: 48,
      jawaban: [
        true,
        true,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
      ],
    },
    {
      nama: "Judy Totterdell",
      skor: 60,
      jawaban: [
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
      ],
    },
  ];

  // const columnHelper = createColumnHelper();

  // const columns = [
  //   columnHelper.accessor("No", {
  //     cell: (info) => info.row.index + 1,
  //     header: () => "No",
  //   }),
  //   columnHelper.accessor("nama", {
  //     cell: (info) => info.getValue(),
  //     footer: (props) => props.column.id,
  //     header: () => "Nama",
  //   }),
  //   columnHelper.group({
  //     header: "Jawaban",
  //     columns: [...jawabanColumns],
  //   }),
  //   columnHelper.accessor("skor", {
  //     cell: (info) => info.getValue(),
  //     header: () => "Skor",
  //   }),
  // ];

  const jawabanColumns = realData[0].jawaban.map((_, index) => ({
    id: `jawaban-${index + 1}`,
    header: () => <span>{index + 1}</span>,
    accessor: (data) => data.jawaban[index],
    cell: (info) => (info.row.original.jawaban[index] ? <Check /> : <X />),
  }));
  const columns = useMemo(() => [
    { header: "No", cell: (info) => info.row.index + 1 },
    {
      header: "Nama",
      accessorKey: "nama",
      cell: (info) => info.getValue(),
    },
    {
      header: "Jawaban",
      columns: jawabanColumns,
    },
  ]);

  return (
    <div>
      <Hero />
      <GetApps />
      <div className="flex justify-center">
        <TableQuiz columns={columns} datas={realData} />
      </div>
      <div className="flex justify-center"></div>
      <div>
        <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank" rel="noreferrer">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <Button
          className="mx-3 bg-slate-600"
          onClick={() => setCount((count) => count + 1)}
          disabled
        >
          count is {count}
        </Button>
        <Button
          className="mx-3 bg-slate-600"
          onClick={() => setCount((count) => count + 1)}
        >
          count is {count}
        </Button>
        <Button variant="outline">Button outline</Button>
        <Button variant="link">
          <a href="/aaa">Link Btn</a>
        </Button>
        <p>
          Edit <code>src/App.jsx</code> and save to test HMR
        </p>
      </div>
      <LandingPages />
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </div>
  );
}

export default App;
